(define (problem tpp-p00_10places_5goals)
(:domain tpp)
(:objects
 mar0 mar1 mar2 mar3 mar4 mar5 mar6 mar7 mar8 mar9 - market
 dep0 dep1 dep2 dep3 dep4 dep5 dep6 dep7 dep8 dep9 - depot
 t0 t1 - truck
 g0 g1 g2 g3 g4 g5 g6 g7 g8 g9 - goods
)
(:init
    (= (total-cost) 0)
    (at t0 dep0)
    (at t1 dep1)
    (connected mar0 dep0)
    (connected dep0 mar0)
    (= (drive-cost dep0 mar0) 10)
    (= (drive-cost dep0 dep0) 10)
    (connected mar0 mar3)
    (connected dep0 dep3)
    (= (drive-cost mar0 mar3) 10)
    (connected mar0 mar7)
    (connected dep0 dep7)
    (= (drive-cost mar0 mar7) 10)
    (connected mar1 dep1)
    (connected dep1 mar1)
    (= (drive-cost dep1 mar1) 10)
    (= (drive-cost dep1 dep1) 10)
    (connected mar1 mar9)
    (connected dep1 dep9)
    (= (drive-cost mar1 mar9) 10)
    (connected mar1 mar6)
    (connected dep1 dep6)
    (= (drive-cost mar1 mar6) 10)
    (connected mar2 dep2)
    (connected dep2 mar2)
    (= (drive-cost dep2 mar2) 10)
    (= (drive-cost dep2 dep2) 10)
    (connected mar2 mar8)
    (connected dep2 dep8)
    (= (drive-cost mar2 mar8) 10)
    (connected mar3 dep3)
    (connected dep3 mar3)
    (= (drive-cost dep3 mar3) 10)
    (= (drive-cost dep3 dep3) 10)
    (connected mar3 mar0)
    (connected dep3 dep0)
    (= (drive-cost mar3 mar0) 10)
    (connected mar4 dep4)
    (connected dep4 mar4)
    (= (drive-cost dep4 mar4) 10)
    (= (drive-cost dep4 dep4) 10)
    (connected mar4 mar5)
    (connected dep4 dep5)
    (= (drive-cost mar4 mar5) 10)
    (connected mar5 dep5)
    (connected dep5 mar5)
    (= (drive-cost dep5 mar5) 10)
    (= (drive-cost dep5 dep5) 10)
    (connected mar5 mar8)
    (connected dep5 dep8)
    (= (drive-cost mar5 mar8) 10)
    (connected mar5 mar9)
    (connected dep5 dep9)
    (= (drive-cost mar5 mar9) 10)
    (connected mar5 mar4)
    (connected dep5 dep4)
    (= (drive-cost mar5 mar4) 10)
    (connected mar5 mar6)
    (connected dep5 dep6)
    (= (drive-cost mar5 mar6) 10)
    (connected mar6 dep6)
    (connected dep6 mar6)
    (= (drive-cost dep6 mar6) 10)
    (= (drive-cost dep6 dep6) 10)
    (connected mar6 mar1)
    (connected dep6 dep1)
    (= (drive-cost mar6 mar1) 10)
    (connected mar6 mar5)
    (connected dep6 dep5)
    (= (drive-cost mar6 mar5) 10)
    (connected mar7 dep7)
    (connected dep7 mar7)
    (= (drive-cost dep7 mar7) 10)
    (= (drive-cost dep7 dep7) 10)
    (connected mar7 mar0)
    (connected dep7 dep0)
    (= (drive-cost mar7 mar0) 10)
    (connected mar8 dep8)
    (connected dep8 mar8)
    (= (drive-cost dep8 mar8) 10)
    (= (drive-cost dep8 dep8) 10)
    (connected mar8 mar2)
    (connected dep8 dep2)
    (= (drive-cost mar8 mar2) 10)
    (connected mar8 mar5)
    (connected dep8 dep5)
    (= (drive-cost mar8 mar5) 10)
    (connected mar9 dep9)
    (connected dep9 mar9)
    (= (drive-cost dep9 mar9) 10)
    (= (drive-cost dep9 dep9) 10)
    (connected mar9 mar1)
    (connected dep9 dep1)
    (= (drive-cost mar9 mar1) 10)
    (connected mar9 mar5)
    (connected dep9 dep5)
    (= (drive-cost mar9 mar5) 10)
    (on-sale g0 mar5)
    (available g0 mar5)
    (= (price g0 mar5) 1)
    (on-sale g1 mar5)
    (available g1 mar5)
    (= (price g1 mar5) 1)
    (on-sale g2 mar5)
    (available g2 mar5)
    (= (price g2 mar5) 1)
    (on-sale g3 mar5)
    (available g3 mar5)
    (= (price g3 mar5) 1)
    (on-sale g4 mar9)
    (available g4 mar9)
    (= (price g4 mar9) 1)
    (on-sale g5 mar9)
    (available g5 mar9)
    (= (price g5 mar9) 1)
    (on-sale g6 mar8)
    (available g6 mar8)
    (= (price g6 mar8) 1)
    (on-sale g7 mar8)
    (available g7 mar8)
    (= (price g7 mar8) 1)
    (on-sale g8 mar6)
    (available g8 mar6)
    (= (price g8 mar6) 1)
    (on-sale g9 mar6)
    (available g9 mar6)
    (= (price g9 mar6) 1)
    (on-sale g10 mar1)
    (available g10 mar1)
    (= (price g10 mar1) 1)
)
(:goal (and
    (stored g0)
    (stored g1)
    (stored g2)
    (stored g3)
    (stored g4)
))
(:metric minimize (total-cost))
)
