(define (problem squirrel_blocks_task)
(:domain squirrel_blocks_contingent)
(:objects
	kenny - robot
box0 box1 - box
ob_block_00 ob_car_00 ob_book_00 ob_block_10 ob_car_10 ob_book_10 - object
wp0 wp1 - waypoint
)
(:init
	(gripper_empty kenny)
	(robot_at kenny wp0)
	(oneof (can_pickup kenny ob_block_00) (can_push kenny ob_block_00))
	(clear ob_block_00)
	(object_at ob_block_00 wp0)
	(oneof (can_pickup kenny ob_car_00) (can_push kenny ob_car_00))
	(oneof (can_pickup kenny ob_book_00) (can_push kenny ob_book_00))
	(clear ob_car_00)
	(clear ob_book_00)
	(object_at ob_car_00 wp0)
	(object_at ob_book_00 wp0)
	(can_stack_on ob_block_00 ob_block_00)
	(can_stack_on ob_block_00 ob_car_00)
	(can_stack_on ob_block_00 ob_book_00)
	(can_stack_on ob_car_00 ob_block_00)
	(can_stack_on ob_book_00 ob_block_00)
	(can_stack_on ob_car_00 ob_car_00)
	(can_stack_on ob_car_00 ob_book_00)
	(can_stack_on ob_book_00 ob_car_00)
	(can_stack_on ob_book_00 ob_book_00)
	(can_fit_inside ob_block_00 box0)
	(can_fit_inside ob_car_00 box0)
	(can_fit_inside ob_book_00 box0)
	(can_stack_on ob_block_00 ob_block_10)
	(can_stack_on ob_block_00 ob_car_10)
	(can_stack_on ob_block_00 ob_book_10)
	(can_stack_on ob_car_00 ob_block_10)
	(can_stack_on ob_book_00 ob_block_10)
	(can_stack_on ob_car_00 ob_car_10)
	(can_stack_on ob_car_00 ob_book_10)
	(can_stack_on ob_book_00 ob_car_10)
	(can_stack_on ob_book_00 ob_book_10)
	(can_fit_inside ob_block_00 box1)
	(can_fit_inside ob_car_00 box1)
	(can_fit_inside ob_book_00 box1)
	(oneof (can_pickup kenny ob_block_10) (can_push kenny ob_block_10))
	(clear ob_block_10)
	(object_at ob_block_10 wp1)
	(oneof (can_pickup kenny ob_car_10) (can_push kenny ob_car_10))
	(oneof (can_pickup kenny ob_book_10) (can_push kenny ob_book_10))
	(clear ob_car_10)
	(clear ob_book_10)
	(object_at ob_car_10 wp1)
	(object_at ob_book_10 wp1)
	(can_stack_on ob_block_10 ob_block_00)
	(can_stack_on ob_block_10 ob_car_00)
	(can_stack_on ob_block_10 ob_book_00)
	(can_stack_on ob_car_10 ob_block_00)
	(can_stack_on ob_book_10 ob_block_00)
	(can_stack_on ob_car_10 ob_car_00)
	(can_stack_on ob_car_10 ob_book_00)
	(can_stack_on ob_book_10 ob_car_00)
	(can_stack_on ob_book_10 ob_book_00)
	(can_fit_inside ob_block_10 box0)
	(can_fit_inside ob_car_10 box0)
	(can_fit_inside ob_book_10 box0)
	(can_stack_on ob_block_10 ob_block_10)
	(can_stack_on ob_block_10 ob_car_10)
	(can_stack_on ob_block_10 ob_book_10)
	(can_stack_on ob_car_10 ob_block_10)
	(can_stack_on ob_book_10 ob_block_10)
	(can_stack_on ob_car_10 ob_car_10)
	(can_stack_on ob_car_10 ob_book_10)
	(can_stack_on ob_book_10 ob_car_10)
	(can_stack_on ob_book_10 ob_book_10)
	(can_fit_inside ob_block_10 box1)
	(can_fit_inside ob_car_10 box1)
	(can_fit_inside ob_book_10 box1)
)
(:goal
	(and
	(object_at ob_block_10 wp0)
	(object_at ob_block_00 wp1)
)))
