(define (problem os-time-p00_5)
(:domain openstacks-time-nonADL-nonNegated)
(:init

(= (total-capacity) 5)
(= (stacks-used) 0)
(waiting o0)
(waiting o1)
(waiting o2)
(waiting o3)
(waiting o4)

(not-made p0)
(has_color_p p0 g)
(has_color_o o0 g)
(has_color_o o1 g)
(has_color_o o2 g)
(has_color_o o3 g)
(not-made p1)
(has_color_p p1 r)
(has_color_o o0 r)
(has_color_o o1 r)
(has_color_o o2 r)
(has_color_o o3 r)
(has_color_o o4 r)
(not-made p2)
(has_color_p p2 y)
(has_color_o o0 y)
(has_color_o o1 y)
(has_color_o o3 y)
(has_color_o o4 y)
(not-made p3)
(has_color_p p3 y)
(has_color_o o0 y)
(has_color_o o2 y)
(has_color_o o3 y)
(has_color_o o4 y)
(not-made p4)
(has_color_p p4 k)
(has_color_o o1 k)
(has_color_o o2 k)
(has_color_o o4 k)

(includes o0 p3)
(includes o0 p0)
(includes o0 p2)
(includes o0 p1)
(includes o1 p0)
(includes o1 p4)
(includes o1 p2)
(includes o1 p1)
(includes o2 p1)
(includes o2 p4)
(includes o2 p0)
(includes o2 p3)
(includes o3 p1)
(includes o3 p2)
(includes o3 p0)
(includes o3 p3)
(includes o4 p1)
(includes o4 p4)
(includes o4 p2)
(includes o4 p3)

)

(:goal (and
(shipped o1)
))
)

