(define (problem os-time-p00_10)
(:domain openstacks-time-nonADL-nonNegated)
(:init

(= (total-capacity) 10)
(= (stacks-used) 0)
(waiting o0)
(waiting o1)
(waiting o2)
(waiting o3)
(waiting o4)
(waiting o5)
(waiting o6)
(waiting o7)
(waiting o8)
(waiting o9)

(not-made p0)
(has_color_p p0 y)
(has_color_o o0 y)
(has_color_o o1 y)
(has_color_o o5 y)
(has_color_o o7 y)
(not-made p1)
(has_color_p p1 r)
(has_color_o o1 r)
(has_color_o o6 r)
(has_color_o o8 r)
(has_color_o o9 r)
(not-made p2)
(has_color_p p2 b)
(has_color_o o3 b)
(has_color_o o5 b)
(has_color_o o9 b)
(not-made p3)
(has_color_p p3 y)
(has_color_o o0 y)
(has_color_o o2 y)
(has_color_o o7 y)
(has_color_o o8 y)
(has_color_o o9 y)
(not-made p4)
(has_color_p p4 k)
(has_color_o o3 k)
(has_color_o o4 k)
(has_color_o o9 k)
(not-made p5)
(has_color_p p5 c)
(has_color_o o2 c)
(has_color_o o4 c)
(has_color_o o5 c)
(has_color_o o6 c)
(not-made p6)
(has_color_p p6 c)
(has_color_o o2 c)
(has_color_o o3 c)
(has_color_o o4 c)
(not-made p7)
(has_color_p p7 r)
(has_color_o o1 r)
(has_color_o o2 r)
(has_color_o o4 r)
(has_color_o o7 r)
(has_color_o o8 r)
(not-made p8)
(has_color_p p8 b)
(has_color_o o0 b)
(has_color_o o1 b)
(has_color_o o6 b)
(not-made p9)
(has_color_p p9 r)
(has_color_o o0 r)
(has_color_o o3 r)
(has_color_o o5 r)
(has_color_o o6 r)
(has_color_o o7 r)
(has_color_o o8 r)

(includes o0 p9)
(includes o0 p0)
(includes o0 p3)
(includes o0 p8)
(includes o1 p0)
(includes o1 p8)
(includes o1 p7)
(includes o1 p1)
(includes o2 p7)
(includes o2 p5)
(includes o2 p3)
(includes o2 p6)
(includes o3 p2)
(includes o3 p4)
(includes o3 p9)
(includes o3 p6)
(includes o4 p7)
(includes o4 p6)
(includes o4 p4)
(includes o4 p5)
(includes o5 p2)
(includes o5 p0)
(includes o5 p9)
(includes o5 p5)
(includes o6 p9)
(includes o6 p5)
(includes o6 p8)
(includes o6 p1)
(includes o7 p9)
(includes o7 p0)
(includes o7 p7)
(includes o7 p3)
(includes o8 p1)
(includes o8 p3)
(includes o8 p7)
(includes o8 p9)
(includes o9 p4)
(includes o9 p1)
(includes o9 p2)
(includes o9 p3)

)

(:goal (and
(shipped o8)
))
)

