(define (problem os-time-p00_15)
(:domain openstacks-time-nonADL-nonNegated)
(:init

(= (total-capacity) 15)
(= (stacks-used) 0)
(waiting o0)
(waiting o1)
(waiting o2)
(waiting o3)
(waiting o4)
(waiting o5)
(waiting o6)
(waiting o7)
(waiting o8)
(waiting o9)
(waiting o10)
(waiting o11)
(waiting o12)
(waiting o13)
(waiting o14)

(not-made p0)
(has_color_p p0 b)
(has_color_o o0 b)
(has_color_o o2 b)
(has_color_o o4 b)
(has_color_o o8 b)
(not-made p1)
(has_color_p p1 b)
(has_color_o o4 b)
(has_color_o o7 b)
(has_color_o o11 b)
(has_color_o o12 b)
(has_color_o o13 b)
(not-made p2)
(has_color_p p2 r)
(has_color_o o1 r)
(has_color_o o3 r)
(has_color_o o6 r)
(has_color_o o12 r)
(not-made p3)
(has_color_p p3 y)
(has_color_o o1 y)
(has_color_o o2 y)
(has_color_o o10 y)
(has_color_o o12 y)
(has_color_o o13 y)
(has_color_o o14 y)
(not-made p4)
(has_color_p p4 b)
(has_color_o o0 b)
(has_color_o o6 b)
(has_color_o o13 b)
(not-made p5)
(has_color_p p5 y)
(has_color_o o0 y)
(has_color_o o4 y)
(has_color_o o5 y)
(has_color_o o9 y)
(not-made p6)
(has_color_p p6 b)
(has_color_o o0 b)
(has_color_o o2 b)
(has_color_o o5 b)
(has_color_o o9 b)
(has_color_o o10 b)
(has_color_o o14 b)
(not-made p7)
(has_color_p p7 c)
(has_color_o o3 c)
(has_color_o o5 c)
(has_color_o o8 c)
(not-made p8)
(has_color_p p8 r)
(has_color_o o1 r)
(has_color_o o2 r)
(has_color_o o3 r)
(has_color_o o5 r)
(has_color_o o11 r)
(not-made p9)
(has_color_p p9 g)
(has_color_o o1 g)
(has_color_o o6 g)
(has_color_o o7 g)
(has_color_o o10 g)
(not-made p10)
(has_color_p p10 y)
(has_color_o o7 y)
(has_color_o o8 y)
(has_color_o o9 y)
(has_color_o o11 y)
(not-made p11)
(has_color_p p11 b)
(has_color_o o10 b)
(not-made p12)
(has_color_p p12 y)
(has_color_o o3 y)
(has_color_o o4 y)
(has_color_o o8 y)
(has_color_o o9 y)
(has_color_o o14 y)
(not-made p13)
(has_color_p p13 r)
(has_color_o o7 r)
(has_color_o o14 r)
(not-made p14)
(has_color_p p14 r)
(has_color_o o6 r)
(has_color_o o11 r)
(has_color_o o12 r)
(has_color_o o13 r)

(includes o0 p0)
(includes o0 p4)
(includes o0 p6)
(includes o0 p5)
(includes o1 p2)
(includes o1 p8)
(includes o1 p9)
(includes o1 p3)
(includes o2 p3)
(includes o2 p0)
(includes o2 p6)
(includes o2 p8)
(includes o3 p7)
(includes o3 p12)
(includes o3 p2)
(includes o3 p8)
(includes o4 p1)
(includes o4 p0)
(includes o4 p12)
(includes o4 p5)
(includes o5 p5)
(includes o5 p6)
(includes o5 p8)
(includes o5 p7)
(includes o6 p4)
(includes o6 p9)
(includes o6 p2)
(includes o6 p14)
(includes o7 p10)
(includes o7 p13)
(includes o7 p1)
(includes o7 p9)
(includes o8 p7)
(includes o8 p12)
(includes o8 p10)
(includes o8 p0)
(includes o9 p6)
(includes o9 p10)
(includes o9 p5)
(includes o9 p12)
(includes o10 p9)
(includes o10 p6)
(includes o10 p11)
(includes o10 p3)
(includes o11 p1)
(includes o11 p14)
(includes o11 p8)
(includes o11 p10)
(includes o12 p3)
(includes o12 p14)
(includes o12 p1)
(includes o12 p2)
(includes o13 p1)
(includes o13 p4)
(includes o13 p14)
(includes o13 p3)
(includes o14 p3)
(includes o14 p12)
(includes o14 p6)
(includes o14 p13)

)

(:goal (and
(shipped o11)
))
)

